#pragma once

// from glfw3.h
#define CRIMSON_MOUSE_BUTTON_1         0
#define CRIMSON_MOUSE_BUTTON_2         1
#define CRIMSON_MOUSE_BUTTON_3         2
#define CRIMSON_MOUSE_BUTTON_4         3
#define CRIMSON_MOUSE_BUTTON_5         4
#define CRIMSON_MOUSE_BUTTON_6         5
#define CRIMSON_MOUSE_BUTTON_7         6
#define CRIMSON_MOUSE_BUTTON_8         7
#define CRIMSON_MOUSE_BUTTON_LAST      CRIMSON_MOUSE_BUTTON_8
#define CRIMSON_MOUSE_BUTTON_LEFT      CRIMSON_MOUSE_BUTTON_1
#define CRIMSON_MOUSE_BUTTON_RIGHT     CRIMSON_MOUSE_BUTTON_2
#define CRIMSON_MOUSE_BUTTON_MIDDLE    CRIMSON_MOUSE_BUTTON_3